# This is a basic workflow that is manually triggered

name: Bump version

on:
  workflow_dispatch:
    inputs:
      fragment:
        description: Next version to create
        required: true
        type: choice
        options:
          - major
          - feature
          - bug
          - rc
          - beta
          - alpha

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo current_version=$(jq -r .version package.json) >> $GITHUB_ENV
      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ env.current_version }}
          version-fragment: ${{ inputs.fragment }}
      - run: echo ${{ steps.bump_version.outputs.next-version }}
      - run: |
          import json
          package = json.load(open("package.json"))
          package["version"] = "${{ steps.bump_version.outputs.next-version }}"
          json.dump(package, open("package.json", "wt"), indent=2)
        shell: python
      - run: |
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'github-actions[bot]'
          git add package.json && \
          git commit -m "Updated to version ${{ steps.bump_version.outputs.next-version }}" && \
          git push origin main
