# This is a basic workflow that is manually triggered

name: Bump version

on:
  workflow_dispatch:
    inputs:
      fragment:
        description: Next version to create
        required: true
        type: choice
        options:
          - major
          - feature
          - bug
          - alpha
          - beta
          - rc

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo current_version=$(jq .version package.json) >> $GITHUB_ENV
      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ env.current_version }}
          version-fragment: ${{ inputs.fragment }}
      - run: echo ${{ steps.bump_version.outputs.next-version }}
