name: Bump version

on:
  workflow_dispatch:
    inputs:
      fragment:
        description: Next version to create
        required: true
        type: choice
        options:
          - major
          - feature
          - bug
          - rc
          - beta
          - alpha

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          jq -r "\"current_version=\" + .version" package.json >> $GITHUB_ENV
      - name: Bump release version
        id: bump_version
        uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: ${{ env.current_version }}
          version-fragment: ${{ inputs.fragment }}
      - run: echo ${{ steps.bump_version.outputs.next-version }}
      - run: |
          import json
          package = json.load(open("package.json"))
          package["version"] = "${{ steps.bump_version.outputs.next-version }}"
          json.dump(package, open("package.json", "wt"), indent=2)
        shell: python
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://npm.pkg.github.com'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global user.name 'github-actions[bot]'
          git add package.json && \
          git commit -m "Updated to version ${{ steps.bump_version.outputs.next-version }}" && \
          git push origin main
      - run: |
          gh release create v${{ steps.bump_version.outputs.next-version }} --generate-notes
