name: Local fun run

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: self-hosted

    steps:
      - run: |
          Start-Process "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
        shell: powershell
