name: Publish release on PR close

on:
  pull_request_target:
    types:
      - closed

jobs:
  check:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          cat <<EOF
          ${{ toJSON(github.event.pull_request) }}
          EOF
      - run: |
          cat <<EOF
          ${{ toJSON(github.event.pull_request.labels.*.name) }}
          EOF
  release:
    needs: check
    if: contains(toJSON(github.event.pull_request.labels.*.name), 'release')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      - id: current
        run: |
          jq -r "\"version=\" + .version" package.json >> $GITHUB_OUTPUT
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://npm.pkg.github.com'
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          gh release create v${{ steps.current.outputs.version }} --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
